language: node_js

node_js:
  - "node"

branches:
  only:
    - master

services:
  - docker
install:
  - yarn
script:
  - yarn build
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t hwasurr/onad_react .
  - docker push hwasurr/onad_react