language: node_js

node_js:
  - "node"

branches:
  only:
    - master
sudo: required

before_install:
  - npm install -g yarn  # yarn을 글로벌로 설치

services:
  - docker
install:
  - yarn
script:
  - yarn build
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t hwasurr/onad_react .
  - docker push hwasurr/onad_react

# slack notification for one channel
notifications:
  slack: onadworkspace:GAoJDTE0OUEwadREAoZizqFz