on:
  pull_request:
    branches: [test]

name: Make Test Infrastructure - aws cdk

jobs:
  deploy:
    name: Make Test Infrastructure - aws cdk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: CDK Diff
        uses: scottbrenner/aws-cdk-action@master
        with:
          args: diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK deploy
        uses: scottbrenner/aws-cdk-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
